language : csharp
solution : SmartHome.sln

install:
  - nuget restore SmartHome.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
script:
  - xbuild /p:Configuration=Release SmartHome.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SmartHome.Tests/bin/Release/SmartHome.Tests.dll